spring:
  datasource:
    url: jdbc:h2:mem:clinica_api_db
    username: admin
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path:/swagger-ui.html
